version: '3.8'

services:

  # utility containers
  pytest:
    build: .
    volumes:
      - ./:/app
    entrypoint: ["poetry", "run", "pytest", "-v", "-s"]
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
      POSTGRES_HOST: postgres_test
    depends_on:
      - postgres_test
  postgres_test:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
  
  # main containers

  server:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: ["uvicorn", "y_social.server.main:app", "--host", "0.0.0.0", "--reload"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
  postgres:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/